
build:
	/home/ntai/Linux_Embedded/gcc-linaro-7.5.0-2019.12-x86_64_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-gcc -o hello_world_BBB hello_world_BBB.c

copy:
	scp hello_world_BBB debian@192.168.7.2:/home/debian

